//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakerySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BKRY_CATEGORY
    {
        public long Id { get; set; }
        public string name { get; set; }
        public byte[] image { get; set; }
        public System.DateTime add_date { get; set; }
        public bool publish { get; set; }
        public string insert_by { get; set; }
    }
}
