//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakerySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BKRY_DELIVERY
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string OrderDetails { get; set; }
        public Nullable<System.DateTime> inserted_dt { get; set; }
        public Nullable<int> DeliveryStatus { get; set; }
        public int PaymentType { get; set; }
    }
}
