//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakerySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUST_FEED
    {
        public int Feedback_Id { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public string feedback { get; set; }
        public string Order_id { get; set; }
        public string Creation_Id { get; set; }
    }
}
