//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakerySystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GetOrderDetail
    {
        public Nullable<int> OrderId { get; set; }
        public string OrderDetails { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> Orderon { get; set; }
        public string personname { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string street { get; set; }
        public string postCode { get; set; }
        public string Delivered { get; set; }
    }
}
