//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakerySystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BKRY_MNGT_SYSEntities : DbContext
    {
        public BKRY_MNGT_SYSEntities()
            : base("name=BKRY_MNGT_SYSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BKRY_ITEMS> BKRY_ITEMS { get; set; }
        public virtual DbSet<SYS_USR_INFO> SYS_USR_INFO { get; set; }
        public virtual DbSet<BKRY_CATEGORY> BKRY_CATEGORY { get; set; }
        public virtual DbSet<BKRY_ORDER> BKRY_ORDER { get; set; }
        public virtual DbSet<LoginDetail> LoginDetails { get; set; }
        public virtual DbSet<BKRY_DELIVERY> BKRY_DELIVERY { get; set; }
        public virtual DbSet<GetOrderDetail> GetOrderDetails { get; set; }
    }
}
