//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakerySystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class LoginDetail
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        [DisplayName("User Name")]
        public string UserName { get; set; }

        [DisplayName("User Password")]
        public string UserPassowrd { get; set; }
        public string MachineIP { get; set; }
        public string OperatingSystem { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> LoginTime { get; set; }
    }
}
